#!/usr/bin/env bash

alias g='git'

# update and publish
alias gp='git pull'
alias gP='git push'

# more compact output
alias gs='git status --short --branch'

# publish current or given branch to remote
alias gPP='git promote'

# diff unstaged changes
alias gd='git diff'
alias gdl='gd --stat'

# diff staged changes
alias gds='gd --staged'
alias gdsl='gds --stat'

# diff with master
alias gdm='gd master'
alias gdsm='gds master'
alias gdlm='gdl master'
alias gdslm='gdsl master'

# diff outgoing
alias gdo='gd "@{u}.."'
alias gdso='gds "@{u}.."'
alias gdlo='gdl "@{u}.."'
alias gdslo='gdsl "@{u}.."'

# diff incoming
alias gdi='gd "..@{u}"'
alias gdsi='gds "..@{u}"'
alias gdli='gdl "..@{u}"'
alias gdsli='gdsl "..@{u}"'

# commit staged changes
alias gc='git commit -v'
alias gci='gc --interactive'
alias gca='gc --all'     # auto stage modified/deleted
alias gcA='gca --amend'  # append to last commit

# list branches (local, and with remotes)
alias gb='git branch'
alias gba='gb --remotes --all'

# clean repo
alias gx='gX --dry-run'
alias gX='git clean -fdx'

# move files
alias gmv='git mv -vk'

# remove files
alias grm='git rm'

# remove path from index
alias grmu='grm --cached'

# remove stale branches
alias grmb='git branch --merged | grep -v "\bmaster\b" | xargs git branch -d'

# remove files ignored since adding
alias grmi='git status --porcelain | egrep -v "^\s*D\b" | cut -c4- | xargs git rm -f'

# checkout branches
alias gco='git checkout'
alias gcom='gco master'
alias gcob='gco -b'  # create new branch

# list commits (short, long, and full)
alias gl='git log --decorate'
alias gls='gl --oneline'
alias gll='gl --numstat --graph'
alias glf='gll --patch'

# list latest commits on branches
alias glb='gl --branches --not --remotes --simplify-by-decoration --oneline'

# list latest commits on branches (including remotes)
alias glbr='gl --branches --simplify-by-decoration --oneline'

# list commits since master
alias glm='gl master..'
alias gllm='gll master..'
alias glfm='glf master..'

# list incoming commits
alias gli='gl "..@{u}"'
alias glli='gll "..@{u}"'
alias glfi='glf "..@{u}"'

# list outgoing commits
alias glo='gl "@{u}.."'
alias gllo='gll "@{u}.."'
alias glfo='glf "@{u}.."'

# list files
alias gls='git ls-files'
alias glsd='gd --name-only'  # changed since last commit
alias glsdm='glsd master'  # changed since master
alias glsdo='glsd "@{u}.."'  # changed since push
alias glsdi='glsd "..@{u}"'  # changed since pull

# rebase branch
alias grb='git rebase'
alias grbm='grb master'
alias grba='grb --abort'
alias grbc='grb --continue'
alias grbi='grb --interactive'

# grep files
alias gg='git grep -I --ignore-case'

# find files
alias gf='git ls-files | grep -i'

# submodules
alias gm='git submodule'
alias gma='gm add'
alias gmrm='gm rm'

# update submodules
alias gmp='gmfor "git pull origin master"'

# cleanup submodules
alias gmx='gmX --dry-run'
alias gmx='gmfor "git clean -fdx --dry-run"'
alias gmX='gmfor "git clean -fdx"'

# abandon changes in all submodules
alias gmR='gmfor "git reset --hard HEAD"'

# exec commands for each submodule
gmfor() {
    # ensure submodules are on master
    gm foreach "git checkout master; $*"
}

# add changes to index
alias ga='git add'
alias gai='git add --patch'
alias gan='git add --intent-to-add'

# unstage changes
alias gu='git reset HEAD --'

# stash changes for later
alias gsl='git stash list'
alias gsa='git stash apply'
alias gsu='git stash-unapply'
alias gsd='git stash show --patch'
alias gss='git stash save'
alias gsS='git stash save --include-untracked'
alias gsP='git stash pop'
alias gsD='git stash drop'
alias gsC='git stash clear'

# fix merge conflicts
alias gfix='git mergetool'

# abandon all changes
alias gnvm='git reset .; git checkout .; git checkout master'

# remove staged changes
alias gr='git reset'
alias grh='gr --hard'

# change directory to the repo root
cdg() {
    local root=$(git root "$@")
    test -d "$root" && cd "$root" || echo "unable to change directory to '$root'" >&2
}
