#!/usr/bin/env sh

alias c='clear'

# verbose by default
alias cp='cp -v'
alias mv='mv -v'

if which trash >/dev/null 2>&1; then
    alias rm='trash'
else
    alias rm='rm -v'
fi

alias ln='ln -vsf'  # symlink by default

# rehash tab completion
alias rh='hash -r'

# unified diffs by default
alias diff='diff -u'
