#!/usr/bin/env bash

alias edit='$EDITOR'
alias v=edit
alias sv=sudoedit

# edit a command
vw() {
    local f=$(command which "$@")
    test -f "$f" && v "$f"
}

# generate code tags recursively
alias vtags='ctags -R'

# edit a tag from ctags file
alias vt='v -t'

# generate help tags for plugins
vht() {
    for dir in ~/.config/nvim/doc ~/.config/nvim/pack/default/start/*/doc; do
        vim -c "helptags $dir" -c q
    done
}

# edit the stdout of a command
vx() {
    "$@" | vim -
}

# edit the std{out,err} of a command
vX() {
    "$@" 2>&1 | vim -
}

# exec command
vc() {
    v -c "$@"
}

# exec command then quit
vcq() {
    v -c "$@" -c q
}

# access vim help directly
vh() {
    v -c "help $*" -c only
}
