#!/usr/bin/env bash

set -eu

stow --no-folding --dir ./files --target ~ --restow home

# Pretend neovim is vim.
ln -sfrn ~/.config/nvim ~/.vim
ln -sfrn ~/.config/nvim/init.vim ~/.vimrc

./scripts/build
